### ISSUE TITLE
Decimal data entry 

### ISSUE THREAD

**Issue by LearnPolkadot** [UnFederalReserve/ReserveLendingAlphaTesters#8]
**Describe the bug**
When entering in amounts that start with a decimal a user must first enter a zero.  When testing habit to enter the decimal then amount and several times so far have almost entered the wrong amount.  Granted this is testing and in real life hopefully I would be paying more attention.

**To Reproduce**
1. Enter a value that being with a (.) in the amount field

**Expected behavior**
Allow entry of decimal without a leading zero

**Screenshots**
attached

Desktop (please complete the following information):

OS: Windows 10 Pro - 20H2
Browser: Brave - Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)
Wallet Version (please complete the following information):
MM - MetaMask - 9.3.0
CB - Coinbase - 23.6.363

![image](https://user-images.githubusercontent.com/71201055/114512827-84b39d80-9c07-11eb-974e-b3fdba75d7ed.png)

**Comment by vladyslav2** [comment]
Fixed, please confirm and close an issue

**Comment by LearnPolkadot** [comment]
Tried testing on two Windows 10 devices using Brave (cleared cache).  Video attached still isn't allowing to start with decimal.  


https://user-images.githubusercontent.com/71201055/114612729-7baae680-9c70-11eb-9619-78a9991a31ea.mp4

**Comment by hskainth** [comment]
I have re-tested this on edge browser and verified fix works on there.

**Comment by Jag1899** [comment]
I've re-tested on Brave Browser (Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)), Chrome (Version 92.0.4476.0 (Official Build) canary (64-bit)) and Firefox 88.0b9 (64-bit)

**Comment by LearnPolkadot** [comment]
Re-tested Windows 10 Pro - 20H2 Brave - Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)

Fix is working
